
import type { Metadata } from "next";
import "./globals.css";
import 'react-datepicker/dist/react-datepicker.css';
import ThemeManager from "@/src/components/ui/components/ThemeManager";

export const metadata: Metadata = {
  title: "BoilerPlate NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={""}>
        <ThemeManager />
          {children}
      </body>
    </html>
  );
}